linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8

linters:
  enable:
    - govet
    - golint
    - gofmt
    - goimports
  disable:
    - errcheck

issues:
  exclude-rules:
    - linters:
        - golint
      text: "should have comment or be unexported" # Example: exclude a specific rule